name: auto-deploy

on: 
  push:

jobs:
  deploy_ca_sandbox:
    strategy:
      matrix:
        region: [cac1]
        name: [1,6,7,8,10,11,12,13,14,15,16,17,18]
    runs-on: ubuntu-latest
    name: s-${{matrix.region}}-${{matrix.name}}
    steps:
      - run: echo terraform apply

  deploy_ca_prod:
    needs: [deploy_ca_sandbox]
    strategy:
      matrix:
        region: [cac1]
        name: [pod1, pod2, pod3, pod4, 3,7,8,9,10,12,13,15,16,17,19,20,22,23,25,26,28,30,31, admin1, archive1, j1, j5, rudder1, z1]
    runs-on: ubuntu-latest
    environment: production
    name: ${{matrix.region}}-${{matrix.name}}
    steps:
      - run: echo terraform apply
  
  deploy_eu_prod: 
    needs: [deploy_ca_sandbox]
    strategy:
      matrix:
        region: [euw2]
        name: [4, j3, rudder3]
    runs-on: ubuntu-latest
    environment: production
    name: ${{matrix.region}}-${{matrix.name}}
    steps:
      - run: echo terraform apply 