# This is a basic workflow to help you get started with Actions

name: on-pr

# Controls when the workflow will run
on: 
  pull_request:
    types: [ open, synchronize ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  circle_ci:
    #if: ${{github.event.changes.body !== undefinied}}
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Tests
        run: sleep $((RANDOM % 60))

  pod_manager:
    #if: ${{github.event.changes.body !== undefinied}}
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Build Image
        run: sleep $((RANDOM % 60))
        
            