name: on-tag

on:
  push:
    tags:
      - "*"

jobs:
  circle_ci:
    runs-on: ubuntu-latest
    steps:
      - name: Non Functional Tests
        run: sleep $((RANDOM % 60))

  update_version_file:
    runs-on: ubuntu-latest
    steps:
      - name: Tests
        run: sleep $((RANDOM % 60))

  pod_manager:
    needs: [update_version_file, circle_ci]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Image
        run: sleep $((RANDOM % 60))

  notify:
    needs: [pod_manager]
    runs-on: ubuntu-latest
    steps:
      - name: send slack message
        run: echo message away

  post_release_merge:
    needs: [notify]
    runs-on: ubuntu-latest
    environment: master
    steps:
      - name: Merge to Master
        run: |
          echo git config --global user.name "github-actions[bot]"
          echo git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          echo git checkout master
          echo git reset --hard GITHUB_REF
          echo git push origin master

  rebase_releasable_prs:
    needs: [post_release_merge]
    runs-on: ubuntu-latest
    environment: master
    steps:
      - name: query by label
        run: echo querying
      - name: rebasing
        run: echo git rebase
